const data = {
    orderData: {
        items: [
            {
                name: "Liquid Super Glue (2oz)",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Starbond-EM-150-Medium-Premium-Cyanoacrylate/dp/B00C32MHJU/ref=sr_1_7_sspa",
                pricePerUnitCents: 1479,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Hot Glue Sticks (300pk)",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Magicfly-Hot-Glue-Gun-Sticks/dp/B07JGP71FP/ref=sxin_17_pa_sp_search_thematic_sspa",
                pricePerUnitCents: 1599,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Duct Tape (5pk)",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Kwtpsg-All-Weather-Multi-Use-Industrial-Professional/dp/B0DFGZD299/ref=sr_1_6",
                pricePerUnitCents: 1299,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Painters Tape (4pk)",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Painters-Painting-Adhesive-Decoration-Labeling/dp/B0BPS5QB4D/ref=sr_1_2_sspa",
                pricePerUnitCents: 599,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Black Vinyl Electrical Tape (5pk)",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Scotch-24413-BA-6-66-Feet-0-007-Inch-Electrical/dp/B009E0VBCS/ref=sr_1_3",
                pricePerUnitCents: 1199,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Colored Vinyl Electrical Tape (6pk)",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Electrical-Waterproof-IndoorOutdoor-High-Temperature-Professional/dp/B0BPYDQ7BS/ref=sr_1_6",
                pricePerUnitCents: 399,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Slip Joint Pliers",
                vendor: "Harbor Freight",
                quantity: 1,
                url: "https://www.harborfreight.com/8-in-3-position-slip-joint-pliers-59169.html",
                pricePerUnitCents: 1999,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "60-40 Tin Lead Rosin Core Solder",
                vendor: "Amazon",
                quantity: 2,
                url: "https://www.amazon.com/dp/B073LHK99Z",
                pricePerUnitCents: 899,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Pinecil Power Cord",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/dp/B09FTBNCQ6",
                pricePerUnitCents: 1299,
                shippingAndHandlingCents: 0,
            },
            {
                name: "Pinecil Power Brick",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/gp/product/B087MFLLCR",
                pricePerUnitCents: 1699,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "18 AWG Silicone Wire",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Silicone-Electrical-Conductor-Parallel-Flexible/dp/B07FMRDP87",
                pricePerUnitCents: 1298,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "16 AWG Silicone Wire",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Silicone-Electrical-Conductor-Parallel-Flexible/dp/B07FMLVF84/",
                pricePerUnitCents: 1588,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "14 AWG Silicone Wire",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Silicone-Electrical-Conductor-Parallel-Flexible/dp/B07FMTCHC1/ref=sr_1_5",
                pricePerUnitCents: 1998,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Micro USB to USB C",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Cable-Matters-Micro-Braided-Jacket/dp/B00UUBRX0Y/ref=sr_1_3",
                pricePerUnitCents: 899,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "NFC Tags",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/NTAG215-Compatible-Programmable-NFC-Enabled-Devices/dp/B08BYG1GQZ/ref=sr_1_10",
                pricePerUnitCents: 1395,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Carbide Burr Set (10pc)",
                vendor: "Amazon",
                quantity: 2,
                url: "https://a.co/d/8U08DR9",
                pricePerUnitCents: 599,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Calipers",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Measuring-Stainless-Micrometer-Fraction-Household/dp/B0BF8FYLWS/ref=sr_1_5",
                pricePerUnitCents: 1599,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Gaft Tape",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/SUNALDO-Residue-Free-Professional-Electrical-Reflective/dp/B0DYK73V46/ref=sr_1_6",
                pricePerUnitCents: 1499,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Electric Screw Driver",
                vendor: "Amazon",
                quantity: 2,
                url: "https://www.amazon.com/Amazon-Brand-Rechargeable-Cordless-Screwdriver/dp/B09PFCX8Q1/ref=sr_1_9",
                pricePerUnitCents: 2247,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Washers",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Stainless-Steel-Washers-Pieces-Sizes/dp/B07ZZ5NJJ9/ref=sr_1_3",
                pricePerUnitCents: 727,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: '6" x 24" x .032" Titanium Sheet',
                vendor: "Sackin Metals",
                quantity: 1,
                url: "https://6al4v.shop/collections/6al4v-titanium-plate/products/titanium-6al4v-plate-032-thick?variant=14252692439084",
                pricePerUnitCents: 2000,
                shippingAndHandlingCents: 0,
            },
            {
                name: '6" x 24" x .071" Titanium Sheet',
                vendor: "Sackin Metals",
                quantity: 1,
                url: "https://6al4v.shop/collections/6al4v-titanium-plate/products/titanium-6al4v-plate-071-thick?variant=14252726026284",
                pricePerUnitCents: 4000,
                shippingAndHandlingCents: 0,
            },
            {
                name: '12" x 12" x .1" Titanium Sheet',
                vendor: "Sackin Metals",
                quantity: 1,
                url: "https://6al4v.shop/collections/6al4v-titanium-plate/products/copy-of-titanium-6al4v-plate-090-thick?variant=14265243172908",
                pricePerUnitCents: 5000,
                shippingAndHandlingCents: 0,
            },
            {
                name: "3mm AR600 Desserts Wedge",
                vendor: "Tricity Laser",
                quantity: 1,
                url: "https://www.tricitylaserinc.com/",
                pricePerUnitCents: 2000,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "2mm AR500 Top Armor",
                vendor: "Tricity Laser",
                quantity: 1,
                url: "https://www.tricitylaserinc.com/",
                pricePerUnitCents: 1000,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "2mm AR500 Retaining Ring",
                vendor: "Tricity Laser",
                quantity: 3,
                url: "https://www.tricitylaserinc.com/",
                pricePerUnitCents: 200,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: '1/4" Diameter, 1/2" Long Shoulder Bolt',
                vendor: "McMaster",
                quantity: 6,
                url: "https://www.mcmaster.com/91259A172/",
                pricePerUnitCents: 315,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: '#10 x 3/4" Plastites (50pk)',
                vendor: "McMaster",
                quantity: 1,
                url: "https://www.mcmaster.com/99512A674/",
                pricePerUnitCents: 1128,
                shippingAndHandlingCents: 0,
                notes: "Delivery: Regular",
            },
            {
                name: "Needle Roller bearing",
                vendor: "Amazon",
                quantity: 2,
                url: "https://www.amazon.com/uxcell-HK1210-Needle-Roller-Bearings/dp/B07GC7ZQMW/ref=sr_1_1_sspa",
                pricePerUnitCents: 729,
                shippingAndHandlingCents: 0,
            },
            {
                name: "M6 Square Nut",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Stainless-Fasteners-Repairs-Professional-Engineering/dp/B0F6CGDDP1/ref=sr_1_6",
                pricePerUnitCents: 699,
                shippingAndHandlingCents: 0,
            },
            {
                name: "M6 20mm Bolt",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/Yinpecly-Stainless-M6-1-0mm-Hexagon-Machine/dp/B0DK53B5KW/ref=sr_1_2_sspa",
                pricePerUnitCents: 699,
                shippingAndHandlingCents: 0,
            },
            {
                name: "Weapon Washer",
                vendor: "Amazon",
                quantity: 1,
                url: "https://www.amazon.com/M12-Stainless-Washers-36-5mm-Diameter/dp/B0CX5FPYJ3/ref=sims_dp_d_dex_popular_subs_t3_v6_d_sccl_2_5/134-5310574-4978308",
                pricePerUnitCents: 899,
                shippingAndHandlingCents: 0,
            },
            {
                name: "M6 30mm standoff",
                vendor: "Mouser",
                quantity: 6,
                url: "https://www.mouser.com/ProductDetail/Wurth-Elektronik/970300611?qs=byeeYqUIh0NurGFlYcfUJQ%3D%3D",
                pricePerUnitCents: 113,
                shippingAndHandlingCents: 0,
            },
            {
                name: "WCP 35t htd5",
                vendor: "WCP",
                quantity: 2,
                url: "https://wcproducts.com/products/htd-timing-belts-9mm-width",
                pricePerUnitCents: 399,
                shippingAndHandlingCents: 0,
            },
            {
                name: "GoBilda 8mm REX 24t",
                vendor: "GoBilda",
                quantity: 2,
                url: "https://www.gobilda.com/3417-series-5mm-htd-pitch-set-screw-pinion-timing-belt-pulley-8mm-rex-bore-24-tooth/",
                pricePerUnitCents: 1299,
                shippingAndHandlingCents: 0,
            },
            {
                name: "GoBilda 14mm bore 24t",
                vendor: "GoBilda",
                quantity: 2,
                url: "https://www.gobilda.com/3411-series-5mm-htd-pitch-aluminum-hub-mount-timing-belt-pulley-14mm-bore-24-tooth/",
                pricePerUnitCents: 1299,
                shippingAndHandlingCents: 0,
            },
            {
                name: "GoBilda 43t htd5",
                vendor: "GoBilda",
                quantity: 2,
                url: "https://www.gobilda.com/5mm-pitch-htd-timing-belt-9mm-width-215mm-pitch-length-43-tooth/",
                pricePerUnitCents: 479,
                shippingAndHandlingCents: 0,
            },
            {
                name: "GoBilda 101t htd5",
                vendor: "GoBilda",
                quantity: 2,
                url: "https://www.gobilda.com/5mm-pitch-htd-timing-belt-9mm-width-505mm-pitch-length-101-tooth/",
                pricePerUnitCents: 679,
                shippingAndHandlingCents: 0,
            },
            {
                name: "1.5mm Red Carbon Fiber",
                vendor: "CNC Madness",
                quantity: 2,
                url: "https://cncmadness.com/materials/carbon-fiber/",
                pricePerUnitCents: 1173,
                shippingAndHandlingCents: 0,
            },
        ],

        contactName: "John Doe",
        contactEmail: "john.doe@utdallas.edu",
        contactPhone: "000-000-0000",
        orgName: "Test Organization",
        justification:
            "These parts are needed for the General team to continue research and development on their project.\n\n",
    },
    formInputs: {
        netID: "dal000000",
        advisor: { name: "John Doe", email: "john.doe@utdallas.edu" },
        eventName: "General Part Orders",
        eventDate: "",
        costCenter: { type: "Student Organization Cost Center" },
    },
}

export default data;